# Generated by Django 5.2.4 on 2025-07-19 01:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_messagecontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagecontact',
            name='date_envoye',
        ),
        migrations.AddField(
            model_name='messagecontact',
            name='date_envoi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
